create tablespace TS_DOCENCIA
	datafile 'df_docencia.dat'
	size 16M
	AUTOEXTEND ON NEXT 1M ;

CREATE USER DOCENCIA IDENTIFIED BY bd 
	DEFAULT TABLESPACE TS_DOCENCIA
	QUOTA 5M ON TS_DOCENCIA;

GRANT CONNECT, CREATE TABLE, CREATE ANY VIEW, CREATE PROCEDURE TO DOCENCIA;

CREATE ROLE R_PROFESOR;
CREATE ROLE R_ALUMNO;
CREATE ROLE R_ADMINISTRATIVO;

GRANT CONNECT TO R_ADMINISTRATIVO;
GRANT INSERT, DELETE, ALTER on DOCENCIA.ALUMNO TO R_ADMINISTRATIVO;
GRANT INSERT, DELETE, ALTER on DOCENCIA.ASIGNATURA TO R_ADMINISTRATIVO;
GRANT INSERT, DELETE, ALTER on DOCENCIA.MATRICULA TO R_ADMINISTRATIVO;

GRANT CONNECT TO R_ALUMNO;
GRANT CONNECT TO R_PROFESOR;

create tablespace ts_index
  datafile 'ts_index.dat'
  size 30M
  AUTOEXTEND ON NEXT 1M;
  
ALTER USER DOCENCIA
	QUOTA 30M ON ts_index;
